docker buildx build \
--label org.opencontainers.image.title=astrabert/local-search-application\
--label org.opencontainers.image.description='Local Search engine container' \
--label org.opencontainers.image.url=https://github.com/AstraBert/qdurllm \
--label org.opencontainers.image.source=https://github.com/AstraBert/qdurllm \
--label org.opencontainers.image.version=0.0.0 \
--label org.opencontainers.image.created=2023-01-13T12:39:11.393Z \
--label org.opencontainers.image.licenses=MIT \
--platform linux/amd64 \
--tag ghcr.io/astrabert/local-search-application:latest \
--push .